# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
env_files:
  github_token: ~/.config/goreleaser/github_token
nfpms:
  - maintainer: Tom LeZotte <tom@lezotte.net>
    vendor: EagleImage
    description: Uncompress different types of archives
    homepage: https://tom.lezotte.net
    license: MIT
#    bindir: /app001/bin
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x64
    formats:
    - deb
    - rpm